### ISSUE TITLE
Import Users (xtuple-server import-users) Results in Qt enabled users but not mobile

### ISSUE THREAD

**Issue by mdathe** [xtuple/xtuple-server-core#478]
I used this Webmin option and it ran perfectly.  I can see and use the users through the Qt client but not through mobile.  It is my understanding that there is a step missing in Import Users and that it (or another option in Webmin must run buildapp.

**Comment by shackbarth** [comment]
Duplicate of https://github.com/xtuple/xtuple-server-core/issues/471
