### ISSUE TITLE
I have trid to set up xtuple server using clean Ubuntu VM same error at stage of intallation

### ISSUE THREAD

**Issue by frankjarr** [xtuple/xtuple-server-core#483]
even that we followed all steps as indicated on github 
we can't pass to installation process https://github.com/xtuple/xtuple-server/wiki/1.-Install
The quickstart (bootstramp) process was done without issues, then when I try to run : 
sudo xtuple-server install-dev 
--xt-demo
--local-workspace ~/dev/xtuple
I got several ERR!VerifyOptions messages, and stop there :-( ...... 
mainly described as : Cannot find module /home/<name>/package.... and so module js.357:17, it is very dissapointing that the server sw is so complicate to install and complete a simple evaluation .... 

Hope someone can help on this matter. 

Kind Regards

**Comment by shackbarth** [comment]
I'd recommend `install-pilot` (as described here: https://github.com/xtuple/xtuple-server/wiki/1.-Install) for kicking the tires of the application. You should only use install-dev if you're planning to contribute code.
